buildings = {'shelter': 0,
             'shed': 0,
             'corral': 0,
             'workshop': 0,
             'outpost': 0
             }

locations = {'Volga banks': {'urban': False,
                             'difficulty': 1,
                             'wood': 6,
                             'food': 30,
                             'freshwater': 50,
                             'dirtywater': 0,
                             'polluted': False},

             'Pine forest': {'urban': False,
                             'difficulty': 1,
                             'wood': 9,
                             'food': 25,
                             'freshwater': 5,
                             'dirtywater': 0,
                             'polluted': False},

             'Belka E': {'urban': False,
                         'difficulty': 2,
                         'wood': 5,
                         'food': 20,
                         'freshwater': 5,
                         'dirtywater': 2,
                         'polluted': False},

             'Belka W': {'urban': False,
                         'difficulty': 3,
                         'wood': 4,
                         'food': 15,
                         'freshwater': 5,
                         'dirtywater': 5,
                         'polluted': False},

             'Blue hills E': {'urban': False,
                              'difficulty': 3,
                              'wood': 20,
                              'food': 10,
                              'freshwater': 0,
                              'dirtywater': 10,
                              'polluted': False},

             'Blue hills W': {'urban': False,
                              'difficulty': 4,
                              'wood': 20,
                              'food': 0,
                              'freshwater': 0,
                              'dirtywater': 20,
                              'polluted': False},

             'Lenin bridge': {'urban': True,
                              'difficulty': 5,
                              'wood': 0,
                              'food': 5,
                              'freshwater': 10,
                              'dirtywater': 30,
                              'polluted': True},

             'Park Svobodi': {'urban': True,
                              'difficulty': 4,
                              'wood': 0,
                              'food': 15,
                              'freshwater': 15,
                              'dirtywater': 60,
                              'polluted': True},

             'Zhukovski': {'urban': True,
                           'difficulty': 5,
                           'wood': 50,
                           'food': 0,
                           'freshwater': 0,
                           'dirtywater': 90,
                           'polluted': True},

             'Desolate marsh': {'urban': False,
                                'difficulty': 4,
                                'wood': 10,
                                'food': 0,
                                'freshwater': 0,
                                'dirtywater': 100,
                                'polluted': True},
}
